# Generated by Django 3.0.5 on 2020-09-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200906_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_type',
        ),
    ]
