# Generated by Django 3.0.5 on 2020-10-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200906_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.ProfileType'),
        ),
    ]
