# Generated by Django 3.0.5 on 2020-10-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20201019_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='account.ProfileType'),
        ),
    ]
