# Generated by Django 3.0.5 on 2020-10-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='working_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
