# Generated by Django 3.0.5 on 2020-11-06 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20201106_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='following',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to='account.Profile'),
        ),
    ]
