# Generated by Django 3.0.5 on 2020-11-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20201106_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='account.UserFollowing', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_to', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_from', to='account.Profile'),
        ),
    ]
