# Generated by Django 3.0.5 on 2020-09-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
