# Generated by Django 3.0.5 on 2020-10-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20201019_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=11, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='post.Category'),
        ),
    ]
