# Generated by Django 3.0.5 on 2020-10-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='likepost',
            name='liked_post',
            field=models.ManyToManyField(related_name='likes', to='post.Post'),
        ),
    ]
