# Generated by Django 3.0.5 on 2020-11-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20201019_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(related_name='likes', to='post.LikePost'),
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='liked_post',
        ),
        migrations.AddField(
            model_name='likepost',
            name='liked_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='post.Post'),
        ),
    ]
