# Generated by Django 3.0.5 on 2020-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20201109_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(related_name='all_likes', to='post.LikePost'),
        ),
    ]
