# Generated by Django 3.0.5 on 2020-11-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20201109_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='liked_post',
        ),
        migrations.AddField(
            model_name='likepost',
            name='liked_post',
            field=models.ManyToManyField(related_name='liked_post', to='post.Post'),
        ),
    ]
